export const musicCardData = [
  {
    id: 1,
    image: 'https://www.hyperui.dev/photos/man-6.jpeg',
    musicTitle: 'Flying Fish',
    musicInfo: 'Fantasy Dream(album)',
    button1: 'Play',
    button2: '$10',
  },
  {
    id: 2,
    image: 'https://www.hyperui.dev/photos/man-6.jpeg',
    musicTitle: 'Flying Fish',
    musicInfo: 'Fantasy Dream(album)',
    button1: 'Play',
    button2: '$10',
  },
  {
    id: 3,
    image: 'https://www.hyperui.dev/photos/man-6.jpeg',
    musicTitle: 'Flying Fish',
    musicInfo: 'Fantasy Dream(album)',
    button1: 'Play',
    button2: '$10',
  },
  {
    id: 4,
    image: 'https://www.hyperui.dev/photos/man-6.jpeg',
    musicTitle: 'Flying Fish',
    musicInfo: 'Fantasy Dream(album)',
    button1: 'Play',
    button2: '$10',
  },
  {
    id: 5,
    image: 'https://www.hyperui.dev/photos/man-6.jpeg',
    musicTitle: 'Flying Fish',
    musicInfo: 'Fantasy Dream(album)',
    button1: 'Play',
    button2: '$10',
  },
  {
    id: 6,
    image: 'https://www.hyperui.dev/photos/man-6.jpeg',
    musicTitle: 'Flying Fish',
    musicInfo: 'Fantasy Dream(album)',
    button1: 'Play',
    button2: '$10',
  },
];
